### ISSUE TITLE
Emoji break syntax highlighting in certain situations

### ISSUE THREAD

**Issue by nabilfreeman** [kevinsawicki/monokai#53] opened 2015-07-11 14:07 UTC
<img width="376" alt="screenshot 2015-07-11 15 05 07" src="https://cloud.githubusercontent.com/assets/2470659/8634022/7315f36e-27de-11e5-9d23-3a5e8456625f.png">

code executes without any problems...

**Comment by svanharmelen** [comment] 2015-08-05 07:10
@nabilfreeman I've reproduced this and it turns out this is a problem with the language grammar, not with this theme package.

If you pull up the developer console and have a look at the assigned classes, you'll notice that as soon as you type/insert for example the :joy: icon, the classes change from the correct classes to `.string.quoted.single.js`. This in turns makes the highlighting change as well, but that is by design of course.

So I suggest you open a new issue with the language package(s) where you experience this behaviour and for now I'll close this one here.

**Closed by svanharmelen** 2015-08-05 07:10 UTC
