### ISSUE TITLE
Failed to activate the monokai theme

### ISSUE THREAD

**Issue by Nitewriter** [kevinsawicki/monokai#61] opened 2015-08-12 14:04 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.4
**Thrown From**: [monokai](https://github.com/kevinsawicki/monokai) package, v0.17.0

### Stack Trace

Failed to activate the monokai theme

```
At variable @green is undefined in /Users/nitewriter/.atom/packages/monokai/index.less:51:15

LessError: variable @green is undefined
  at /Users/nitewriter/.atom/packages/monokai/index.less:51:15
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-log, v0.4.1
linter, v1.3.4
pretty-json, v0.4.1
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by svanharmelen** [comment] 2015-08-12 14:17
@Nitewriter are you getting this consistently? Or at least every now and then? Or did you hit this one time only?

I'm asking as I cannot reproduce this issue with the same combination of versions...

**Comment by Nitewriter** [comment] 2015-08-14 13:32
No, it cleared up after a reinstall. Probably a weird edge case while updating Atom and the theme at the same time. 

-Joel

**Comment by svanharmelen** [comment] 2015-08-14 14:18
@Nitewriter thanks for the feedback... I'll close this one for now, but of course you welcome to open it again whenever you notice this again!

**Closed by svanharmelen** 2015-08-14 14:18 UTC
Labels: waiting for reply

**Comment by denislins** [comment] 2015-08-21 18:24
This happened to me too, just now. I reinstalled Atom after three months, and it asked me to update some deprecated modules (I just removed the app from the Applications folder before). After I went to the updates tab, it also asked me to update the monokai theme, and I got this exact same error.

Running OSX 10.10.5, Atom 1.0.7, Monokai 0.18.0.

**Comment by rhettc** [comment] 2015-09-02 18:33
Fresh install of Atom 1.0.10  on Ubuntu 15.04. 
* Uninstalled theme
* Relaunched Atom
* Installed theme
* Resolved

**Comment by marcelocd** [comment] 2020-11-18 13:48
I corrected it.

Use this one: https://github.com/marcelocd/monokai
