### ISSUE TITLE
<htmltag> should be all of the same color?

### ISSUE THREAD

**Issue by grigio** [kevinsawicki/monokai#17] opened 2014-06-09 16:52 UTC
I fixed with this
```
.punctuation.definition.tag.html {
  color: #F92672;
}
```
so the a `<tag>` is all of the same color (fuchsia)

**Comment by svanharmelen** [comment] 2015-08-07 11:36
@grigio could you check if this issue still persists when using the latest version of this theme? I think the problem is solved, but if not please send me a screenshot so I can see the exact issue myself.

Thanks!

**Comment by grigio** [comment] 2015-08-07 11:46
no it isn't fixed.. but maybe it depends of the taste of the theme author

![schermata 2015-08-07 alle 13 41 56](https://cloud.githubusercontent.com/assets/8074/9135090/5a313f3e-3d0a-11e5-88c1-be7eafa49cb2.png)
Atom Dark: the "<" "/>" have the same color of the HTML tag.. +1 I like it

![schermata 2015-08-07 alle 13 42 40](https://cloud.githubusercontent.com/assets/8074/9135110/83be4734-3d0a-11e5-9eba-9ea8861e7a54.png)
Monokai, (but also other themes) have a different color for "<" "/>"

**Comment by svanharmelen** [comment] 2015-08-07 12:23
Ah... Yes... Well that is indeed pretty much as intended I'm afraid.

After testing some other themes as well, it seems `Atom Dark` is actually the only theme (at least of the default themes that come with Atom) that colours the brackets the same as the text. The others all use a variation of white for the brackets.

Next to that I think the current colouring is what people would expect it to be (with regards to these brackets at least) when using a Monokai theme. If I compare this with Monokai themes for other editors, they all seem to have a variation of white for the brackets as well.

So I'm sorry but I will close this one as a won't fix as I prefer to not change this.

**Closed by svanharmelen** 2015-08-07 12:23 UTC
